/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppFxRouteImport } from './routes/app.fx'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppLogisticsRouteImport } from './routes/app.logistics'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppPaymentsIndexRouteImport } from './routes/app.payments.index'
import { Route as AppPaymentsIdRouteImport } from './routes/app.payments.$id'
import { Route as AppPaymentsCommissionsRouteImport } from './routes/app.payments.commissions'
import { Route as AppPaymentsLedgerRouteImport } from './routes/app.payments.ledger'
import { Route as AppPaymentsNewRouteImport } from './routes/app.payments.new'
import { Route as AppPaymentsRecurringRouteImport } from './routes/app.payments.recurring'
import { Route as AppSourcingIndexRouteImport } from './routes/app.sourcing.index'
import { Route as AppSourcingIdRouteImport } from './routes/app.sourcing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppFxRoute = AppFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsIdRoute = AppPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsCommissionsRoute = AppPaymentsCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsLedgerRoute = AppPaymentsLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsNewRoute = AppPaymentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppPaymentsRecurringRoute = AppPaymentsRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppPaymentsRoute,
} as any)
const AppSourcingIndexRoute = AppSourcingIndexRouteImport.update({
  id: '/sourcing/',
  path: '/sourcing/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcingIdRoute = AppSourcingIdRouteImport.update({
  id: '/sourcing/$id',
  path: '/sourcing/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/fx': typeof AppFxRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/market': typeof AppMarketRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal/$token': typeof PortalTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/payments/commissions': typeof AppPaymentsCommissionsRoute
  '/app/payments/ledger': typeof AppPaymentsLedgerRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/payments/recurring': typeof AppPaymentsRecurringRoute
  '/app/sourcing/$id': typeof AppSourcingIdRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/sourcing/': typeof AppSourcingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/fx': typeof AppFxRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/market': typeof AppMarketRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal/$token': typeof PortalTokenRoute
  '/app': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/payments/commissions': typeof AppPaymentsCommissionsRoute
  '/app/payments/ledger': typeof AppPaymentsLedgerRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/payments/recurring': typeof AppPaymentsRecurringRoute
  '/app/sourcing/$id': typeof AppSourcingIdRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/payments': typeof AppPaymentsIndexRoute
  '/app/sourcing': typeof AppSourcingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/fx': typeof AppFxRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/market': typeof AppMarketRoute
  '/app/payments': typeof AppPaymentsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal/$token': typeof PortalTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/payments/$id': typeof AppPaymentsIdRoute
  '/app/payments/commissions': typeof AppPaymentsCommissionsRoute
  '/app/payments/ledger': typeof AppPaymentsLedgerRoute
  '/app/payments/new': typeof AppPaymentsNewRoute
  '/app/payments/recurring': typeof AppPaymentsRecurringRoute
  '/app/sourcing/$id': typeof AppSourcingIdRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/payments/': typeof AppPaymentsIndexRoute
  '/app/sourcing/': typeof AppSourcingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/agents'
    | '/app/clients'
    | '/app/fx'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/market'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/auth/callback'
    | '/portal/$token'
    | '/app/'
    | '/app/orders/$id'
    | '/app/payments/$id'
    | '/app/payments/commissions'
    | '/app/payments/ledger'
    | '/app/payments/new'
    | '/app/payments/recurring'
    | '/app/sourcing/$id'
    | '/app/orders/'
    | '/app/payments/'
    | '/app/sourcing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/agents'
    | '/app/clients'
    | '/app/fx'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/market'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/auth/callback'
    | '/portal/$token'
    | '/app'
    | '/app/orders/$id'
    | '/app/payments/$id'
    | '/app/payments/commissions'
    | '/app/payments/ledger'
    | '/app/payments/new'
    | '/app/payments/recurring'
    | '/app/sourcing/$id'
    | '/app/orders'
    | '/app/payments'
    | '/app/sourcing'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/agents'
    | '/app/clients'
    | '/app/fx'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/market'
    | '/app/payments'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/auth/callback'
    | '/portal/$token'
    | '/app/'
    | '/app/orders/$id'
    | '/app/payments/$id'
    | '/app/payments/commissions'
    | '/app/payments/ledger'
    | '/app/payments/new'
    | '/app/payments/recurring'
    | '/app/sourcing/$id'
    | '/app/orders/'
    | '/app/payments/'
    | '/app/sourcing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fx': {
      id: '/app/fx'
      path: '/fx'
      fullPath: '/app/fx'
      preLoaderRoute: typeof AppFxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics': {
      id: '/app/logistics'
      path: '/logistics'
      fullPath: '/app/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments/': {
      id: '/app/payments/'
      path: '/'
      fullPath: '/app/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/$id': {
      id: '/app/payments/$id'
      path: '/$id'
      fullPath: '/app/payments/$id'
      preLoaderRoute: typeof AppPaymentsIdRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/commissions': {
      id: '/app/payments/commissions'
      path: '/commissions'
      fullPath: '/app/payments/commissions'
      preLoaderRoute: typeof AppPaymentsCommissionsRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/ledger': {
      id: '/app/payments/ledger'
      path: '/ledger'
      fullPath: '/app/payments/ledger'
      preLoaderRoute: typeof AppPaymentsLedgerRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/new': {
      id: '/app/payments/new'
      path: '/new'
      fullPath: '/app/payments/new'
      preLoaderRoute: typeof AppPaymentsNewRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/payments/recurring': {
      id: '/app/payments/recurring'
      path: '/recurring'
      fullPath: '/app/payments/recurring'
      preLoaderRoute: typeof AppPaymentsRecurringRouteImport
      parentRoute: typeof AppPaymentsRoute
    }
    '/app/sourcing/': {
      id: '/app/sourcing/'
      path: '/sourcing'
      fullPath: '/app/sourcing/'
      preLoaderRoute: typeof AppSourcingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sourcing/$id': {
      id: '/app/sourcing/$id'
      path: '/sourcing/$id'
      fullPath: '/app/sourcing/$id'
      preLoaderRoute: typeof AppSourcingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPaymentsRouteChildren {
  AppPaymentsIdRoute: typeof AppPaymentsIdRoute
  AppPaymentsCommissionsRoute: typeof AppPaymentsCommissionsRoute
  AppPaymentsLedgerRoute: typeof AppPaymentsLedgerRoute
  AppPaymentsNewRoute: typeof AppPaymentsNewRoute
  AppPaymentsRecurringRoute: typeof AppPaymentsRecurringRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
}

const AppPaymentsRouteChildren: AppPaymentsRouteChildren = {
  AppPaymentsIdRoute: AppPaymentsIdRoute,
  AppPaymentsCommissionsRoute: AppPaymentsCommissionsRoute,
  AppPaymentsLedgerRoute: AppPaymentsLedgerRoute,
  AppPaymentsNewRoute: AppPaymentsNewRoute,
  AppPaymentsRecurringRoute: AppPaymentsRecurringRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
}

const AppPaymentsRouteWithChildren = AppPaymentsRoute._addFileChildren(
  AppPaymentsRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppFxRoute: typeof AppFxRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppMarketRoute: typeof AppMarketRoute
  AppPaymentsRoute: typeof AppPaymentsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppSourcingIdRoute: typeof AppSourcingIdRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppSourcingIndexRoute: typeof AppSourcingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppClientsRoute: AppClientsRoute,
  AppFxRoute: AppFxRoute,
  AppInboxRoute: AppInboxRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppMarketRoute: AppMarketRoute,
  AppPaymentsRoute: AppPaymentsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppSourcingIdRoute: AppSourcingIdRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppSourcingIndexRoute: AppSourcingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
