/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgentsRouteImport } from './routes/app.agents'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppFxRouteImport } from './routes/app.fx'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppLogisticsRouteImport } from './routes/app.logistics'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppSourcingIndexRouteImport } from './routes/app.sourcing.index'
import { Route as AppSourcingIdRouteImport } from './routes/app.sourcing.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppFxRoute = AppFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcingIndexRoute = AppSourcingIndexRouteImport.update({
  id: '/sourcing/',
  path: '/sourcing/',
  getParentRoute: () => AppRoute,
} as any)
const AppSourcingIdRoute = AppSourcingIdRouteImport.update({
  id: '/sourcing/$id',
  path: '/sourcing/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/fx': typeof AppFxRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/market': typeof AppMarketRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/sourcing/$id': typeof AppSourcingIdRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/sourcing/': typeof AppSourcingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/agents': typeof AppAgentsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/fx': typeof AppFxRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/market': typeof AppMarketRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/sourcing/$id': typeof AppSourcingIdRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/sourcing': typeof AppSourcingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/agents': typeof AppAgentsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/fx': typeof AppFxRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/market': typeof AppMarketRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/': typeof AppIndexRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/sourcing/$id': typeof AppSourcingIdRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/sourcing/': typeof AppSourcingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/clients'
    | '/app/fx'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/market'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/'
    | '/app/orders/$id'
    | '/app/sourcing/$id'
    | '/app/orders/'
    | '/app/sourcing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/agents'
    | '/app/clients'
    | '/app/fx'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/market'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app'
    | '/app/orders/$id'
    | '/app/sourcing/$id'
    | '/app/orders'
    | '/app/sourcing'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/agents'
    | '/app/clients'
    | '/app/fx'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/logistics'
    | '/app/market'
    | '/app/reports'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/'
    | '/app/orders/$id'
    | '/app/sourcing/$id'
    | '/app/orders/'
    | '/app/sourcing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agents': {
      id: '/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fx': {
      id: '/app/fx'
      path: '/fx'
      fullPath: '/app/fx'
      preLoaderRoute: typeof AppFxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics': {
      id: '/app/logistics'
      path: '/logistics'
      fullPath: '/app/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sourcing/': {
      id: '/app/sourcing/'
      path: '/sourcing'
      fullPath: '/app/sourcing/'
      preLoaderRoute: typeof AppSourcingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sourcing/$id': {
      id: '/app/sourcing/$id'
      path: '/sourcing/$id'
      fullPath: '/app/sourcing/$id'
      preLoaderRoute: typeof AppSourcingIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppFxRoute: typeof AppFxRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppMarketRoute: typeof AppMarketRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppSourcingIdRoute: typeof AppSourcingIdRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppSourcingIndexRoute: typeof AppSourcingIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRoute,
  AppClientsRoute: AppClientsRoute,
  AppFxRoute: AppFxRoute,
  AppInboxRoute: AppInboxRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppMarketRoute: AppMarketRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppIndexRoute: AppIndexRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppSourcingIdRoute: AppSourcingIdRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppSourcingIndexRoute: AppSourcingIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
